---
title: "R Notebook"
output: html_notebook
---
# install packages
```{r}
#install.packages("tidyverse",dependencies = TRUE)
#install.packages("ggthemes", dependencies = FALSE)
```
# load packages
```{r}
library(tidyverse)
library(ggthemes)
library(ggplot2)
```
# import data

```{r}
exp1 = read_csv("exp1.csv")

nrow(exp1)

ncol(exp1)

colnames(exp1)

hist(exp1$rt)
```
# Horchak & Garrido
```{r}
condition_data = exp1 %>%
select(subject, rt, typeoftrial, trialcondition, correct)%>%
filter(typeoftrial == "picture" &
         trialcondition %in%
c("Heavy_Normal", "Light_Smashed", "Heavy_Smashed", "Light_Normal"))

condition_data = condition_data %>%
  separate(trialcondition, into = c("weight", "shape"), sep = "_")


# condition_data %>% group_by(subject, trialcondition) %>% count()
```
# exercise
```{r}
exp1 %>%
select(dataset, correct, typeoftrial) %>%
filter(correct == 1 & typeoftrial == "picture")
```
# Horchak & Garrido means
```{r}
means = condition_data %>%
  group_by(weight, shape)%>%
  summarise(mean_rt = mean(rt),
    sd_rt = sd(rt),
    mean_acc = mean(correct))
```

# ggplot basics
```{r}
library(ggplot2)
library(ggthemes)

condition_data %>%
  filter(rt <25000)%>%
  ggplot(aes(x = rt)) +
  geom_histogram(binwidth = 1000,
                 fill = "red", color = "black",
                 position = "identity") +
  theme_few()+
  xlab("RT (in milliseconds)") +
  ylab("Count") +
  ggtitle("Histogram of RT")
```
# Horchak & Garrido
```{r}
means %>%
  ggplot(aes(x=shape, y=mean_rt, fill = weight))+
  geom_col(position = "dodge")+
  theme_fivethirtyeight()+
  labs(x = "shape", y = "mean RT", title = "Barplot of RT")

#another way to write xlab is labs(x = "", y = "", title = "")

```

# read 
```{r}
df = read_csv("relatedness_exp.csv")
```
# class exercises
```{r}
part_df = df %>%
  select(ID, Type, pathlength, RT)%>%
  filter(Type == "Related" & pathlength %in%
  c(1,2))
```

# exercise 2
```{r}
mean_all = df %>%
  summarize(mean = mean(RT))

mean_part = part_df %>%
  summarize(mean = mean(RT))

mean_ID = df %>%
  group_by(ID) %>%
  summarize(mean = mean(RT))
  
```

```{r}
df %>%
group_by(ID)%>%
count()

```
```{r}
df %>%
  group_by(ID, pathlength) %>%
  count()
```
# exercise 5 oct 18
```{r}
mean_condition = df %>%
  group_by(Type, pathlength) %>%
  summarize(mean = mean(RT))

mean_condition %>%
  ggplot(aes(x = pathlength, y = mean, fill = Type))+
  geom_col(position = "dodge")+
  theme_fivethirtyeight()+
  labs(x = "path length", y = "RT", title = "Barplot of RT")


```

# tidyverse mutate function
```{r}
df = df %>%
  mutate(RT_seconds = RT/1000, accuracy = ifelse(pathlength ==1 & Type == "Related", 1, 0))

df = df %>%
  mutate(pathlength = as.factor(pathlength), Type = as.factor(Type))
```

# pull
```{r}
df %>% pull (Type)
df %>% pull (RT)
```

```{r}
levels(df %>% pull (pathlength))
```

# unique
```{r}
df %>% pull (ID) %>% unique()
df %>% pull (response) %>% unique()
unique(c(1,3,3,4,5,5,1,2))

```

# Oct 20: Wide Data Conversion
```{r}
df_wide1 = mean_condition %>%
  pivot_wider(names_from = pathlength, values_from = mean)

df_wide2 = mean_condition %>%
  pivot_wider(names_from = Type, values_from = mean)
```

```{r}
exp1_wide = means %>%
  select(weight, shape, mean_rt) %>%
  pivot_wider(names_from = weight, values_from = mean_rt)
```

```{r}
mean_subject = condition_data %>%
group_by(subject, weight, shape) %>%
  summarize(mean_rt = mean(rt))
```

```{r}
subject_wide = mean_subject %>%
  pivot_wider(names_from = c(weight, shape), values_from = mean_rt)
```

# T-Test
```{r}
t.test(subject_wide$Heavy_Normal, subject_wide$Heavy_Smashed)
```

```{r}
mean_subject %>%
  filter(weight == "Heavy") %>% t.test(mean_rt ~ shape, data=.)
```

# Verifying R output
```{r}
x1_bar = mean(subject_wide$Heavy_Normal)
x2_bar = subject_wide %>% pull(Heavy_Smashed) %>% mean()

s1 = sd(subject_wide$Heavy_Normal)
s2 = subject_wide %>% pull(Heavy_Smashed) %>% sd()

n1 = nrow(subject_wide)
n2 = subject_wide %>% pull(Heavy_Smashed) %>% length()
```

```{r}
t_numerator = x1_bar - x2_bar
inside_root1 = s1*s1/n1
inside_root2 = s2*s2/n2
t_denominator = sqrt(inside_root1 + inside_root2)
t = t_numerator/t_denominator
```

